os:
  - osx

# a little white lie below, to try to force osx on travis-ci
language:
  - objective-c

before_install:
  - brew update
  - brew list

install:
  - curl -sL http://git.io/bootslap > /tmp/bootslap

script:
  - yes | bash /tmp/bootslap

