---
- name: configure shell environment for current user
  hosts: all
  tags: shell
  tasks:
    - name:     compare user current shell to /bin/zsh
      command:  dscl . -read /Users/{{ ansible_user_id }} UserShell
      register: usershell
      changed_when: usershell.stdout.find(' /bin/zsh') == -1

    - name:  change default shell to /bin/zsh
      shell: chsh -s /bin/zsh {{ ansible_user_id }}
      when:  usershell.stdout.find(' /bin/zsh') == -1


- name: install ohmyzsh for current user
  hosts: all
  gather_facts: no
  tags: ohmyzsh
  tasks:
    - name: install oh-my-zsh
      git:  repo=git://github.com/robbyrussell/oh-my-zsh.git
            dest=~/.oh-my-zsh
            update=no

    - name: install syntax highlight plugin for ohmyzsh
      git:  repo=git://github.com/zsh-users/zsh-syntax-highlighting.git
            dest=~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
            update=yes


- name: dotfiles
  hosts: all
  gather_facts: no
  tags: dotfiles
  tasks:
    - name: homeshick | homeshick cloned
      git:  repo=https://github.com/andsens/homeshick.git
            dest=~/.homesick/repos/homeshick
            update=no

    - name: homeshick | homeshick symlinked
      file: src=~/.homesick/repos/homeshick/home/.homeshick
            dest=~/.homeshick
            state=link

    # TODO: parameterize
    - name: homeshick | dotfiles cloned
      git:  repo=https://github.com/mroth/dotfiles.git
            dest=~/.homesick/repos/dotfiles
            update=no
      register: dotfiles_cloned

    - name: homeshick | dotfiles force link if just first installed
      when: dotfiles_cloned|changed
      command: ~/.homeshick link dotfiles --force


- name: vim-janus
  hosts: all
  gather_facts: no
  tags: vimjanus
  tasks:
    - name: install vim-janus
      git: repo=https://github.com/carlhuda/janus.git
           dest=~/.vim
           update=no
           recursive=no
      register: janus_cloned

    - name: bootstrap vim-janus if just first installed
      when: janus_cloned|changed
      command: rake chdir=~/.vim


- name: install scm_breeze
  hosts: all
  gather_facts: no
  tags: scmbreeze
  tasks:
    - name: install scm_breeze
      git: repo=https://github.com/ndbroadbent/scm_breeze.git
           dest=~/.scm_breeze
           update=yes
