---
- name: Ruby Development Environment
  hosts: all
  tags: ruby
  vars:
    default_gems:
      - bundler

  tasks:
    - name: install latest homebrew Ruby
      homebrew: name=ruby state=latest

    - name: install desired global RubyGems
      gem:
        name: "{{ item }}"
        state: present
        user_install: no
        executable: '/usr/local/bin/gem' # make sure we use homebrew version
      with_items: "{{ default_gems }}"

    - name: cleanup old brews from when I was using rbenv
      homebrew: name={{ item }} state=absent
      with_items:
        - rbenv
        - ruby-build
        - rbenv-default-gems

    - name: cleanup old ~/.rbenv data 
      file: path=~/.rbenv state=absent
