---
- name: Rust Development Environment
  hosts: all
  tags: rust

  tasks:
    - name: install homebrew bottle of rust
      homebrew: name=rust state=present

    - name: no longer use cask binary of rust nightlies
      homebrew_cask: name=rust state=absent

    # TODO: use multirust/rustup and install stable and nightly?
    # or maybe we can hope rust gets its act together by time we need this next,
    # and nightly no longer required for day to day development.
